### ISSUE TITLE
Nothing after start SiriProxy

### ISSUE THREAD

**Issue by Enophi** [plamoni/SiriProxy#152]
Hello everybody,

Sorry for my english but when i start SiriProxy. It show up "Starting SiriProxy on port 443.." and after that, nothing happen when i try "Test siri proxy". Any ideas ?

Thx a lot

**Comment by dcinzona** [comment]
your dns on your phone isnt pointing to the siriproxy server ip

**Comment by Enophi** [comment]
The problem is my iPhone IS pointing to the siriproxy server :S

**Comment by dcinzona** [comment]
how are you verifying the DNS settings on your phone?  Just curious.  I use scanny and port scan guzzoni.apple.com.  This then resolves to my internal proxy server.

**Comment by Enophi** [comment]
I use zTools and ping / scanport guzzoni.apple.com. This resolve to my proxy server. Maybe the certificates aren't good.

**Comment by Enophi** [comment]
Oh ! I'm sorry but is it possible that doesn't work because i'm using an iPhone 4 ?

**Comment by dcinzona** [comment]
lol yeah... it wont work on a iPhone 4 without jailbreaking and severe modding.

**Comment by Enophi** [comment]
It is jailbreak.  h1Siri is installed.

**Comment by dcinzona** [comment]
no idea.  out of my realm.  I know that on a stock 4s, it should be working.  mine does

**Comment by LinusU** [comment]
If I'm not totally wrong, the h1Siri hack doesn't send the data to guzzoni.apple.com but to one of the h1Siri creators server. You might be able to use Wireshark to see witch server it is sending to and then redirecting that traffic to your SiriProxy server.

**Comment by Enophi** [comment]
Ok ! Thanks to you guys :)

**Comment by Enophi** [comment]
So...I found this address : 50.97.0.138 ( siri.cd-team.org ). My SiriProxy receive a connection but it seems still don't work.

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xa155900 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xa15d808>, @zip_stream=#Zlib::Deflate:0xa15d7f4, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9da7e20 @manager=#<SiriProxy::PluginManager:0xa15d5c4 @plugins=[...]>>]

**Comment by dcinzona** [comment]
so, your phone thinks guzzoni.apple.com is at 50.97.0.138?
It should be the same IP address as your siriproxy server

**Comment by Enophi** [comment]
For me it isn't guzzoni.apple.com. I'm using an iPhone 4 with h1siri which use Siri.cd-team.org (found 50.97.0.138 with Wireshark) I replace in the dnsmasq.conf guzzoni.apple.com by siri.cd-team.org. But should i recreate certs ?

**Comment by plamoni** [comment]
We do not support or condone piracy in any way around here. Do not respond to issues posted by people running (or trying to run) Siri on a non-iPhone 4S.

**Comment by Enophi** [comment]
Ok. Sorry for that. I dont want to piracy anything but just use this awsome tool to create plugins
