### ISSUE TITLE
Rake Install error/Abort

### ISSUE THREAD

**Issue by huntsept** [plamoni/SiriProxy#165]
I keep on getting this dang Rake Aborted error message. Using lion  and i am using a Direct clone so they are credible files. I have gone over it and over it...... I don't know how to fix it it seems like a pretty straight forward error but there is no reasoning for the abortion. Thanks :)

unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ rake install --trace
*\* Invoke install (first_time)
*\* Execute install
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
rake aborted!
Couldn't install gem, run `gem install /Users/Huntington/Sites/Siri/plamoni-SiriProxy-5ee281c/pkg/siriproxy-0.3.0.gem' for more detailed output
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.0.21/lib/bundler/gem_helper.rb:57:in`install_gem'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@global/gems/bundler-1.0.21/lib/bundler/gem_helper.rb:33:in `block in install'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/Users/Huntington/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/rake:19:in`load'
/Users/Huntington/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/rake:19:in `<main>'
Tasks: TOP => install

**Comment by sudoname** [comment]
try rvm use 1.9.3-p0 --default i hav to do like after every command... my lion seem to forget that i did that 2 commands ago

**Comment by huntsept** [comment]
ok i figured out, i used this gem install /Users/Huntington/Sites/Siri/plamoni-SiriProxy-5ee281c/pkg/siriproxy-0.3.0.gem
to get this nknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ rake install
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
siriproxy (0.3.0) installed

but then l8r
got this
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ mkdir ~/.siriproxy
mkdir: /Users/Huntington/.siriproxy: File exists

which i believed i fixed with 
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ sudo mkdir /siriproxy 
but then couldn't do this
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ ./siriproxy gencerts
-bash: ./siriproxy: is a directory
 so i tried this
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ cd SiriProxy
then
unknown60334b0ed5bb:SiriProxy Huntington$ siriproxy gencert
-bash: siriproxy: command not found
so thats where I'm at now :/

**Comment by venom420x** [comment]
you didn't fix anything with sudo mkdir /siriproxy
its suppose to be ~/.siriproxy if it says it already exists that means proceed to the next command which is 

cp ./config.example.yml ~/.siriproxy/config.yml

then do siriproxy gencerts

make sure you restart your terminal as sometimes it wont recognize that your paths have been updated

**Comment by huntsept** [comment]
This is quite frustrating..... :( but i also restarted the terminal and re-entered the commands and i still end up with the same messages. Thanks for the help so far though.

unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ cp ./config.example.yml ~/.siriproxy/config.yml
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ mkdir ~/.siriproxy
mkdir: /Users/Huntington/.siriproxy: File exists
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ sudo port install openssl
sudo: port: command not found
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ cp ./config.example.yml ~/.siriproxy/config.yml
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ ./siriproxy gencerts
-bash: ./siriproxy: is a directory
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ siriproxy gencerts
-bash: siriproxy: command not found
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$

**Comment by huntsept** [comment]
Now i have attempted with a bundle install

unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ bundle exec siriproxy gencerts
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ bundle install
Fetching git://github.com/chendo/cora.git
remote: Counting objects: 215, done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 215 (delta 91), reused 169 (delta 45)
Receiving objects: 100% (215/215), 23.07 KiB, done.
Resolving deltas: 100% (91/91), done.
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2) 
Installing libxml-ruby (2.2.2) with native extensions 
Installing CFPropertyList (2.0.17) 
Using cora (0.0.3) from git://github.com/chendo/cora.git (at master) 
Installing eventmachine (0.12.10) with native extensions 
Installing uuidtools (2.1.2) 
Using siriproxy (0.3.0) from source at /Users/Huntington/Sites/Siri/plamoni-SiriProxy-5ee281c 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ bundle exec siriproxy gencerts
/Users/Huntington/Sites/Siri/plamoni-SiriProxy-5ee281c/SiriProxy/bin/siriproxy:4:in `require': /Users/Huntington/Sites/Siri/plamoni-SiriProxy-5ee281c/SiriProxy/bin/../lib/siriproxy/command_line.rb:74: syntax error, unexpected '>' (SyntaxError)
    repl = -> prompt { print prompt; cora.process(gets.chomp!) }
             ^
    from /Users/Huntington/Sites/Siri/plamoni-SiriProxy-5ee281c/SiriProxy/bin/siriproxy:4
    from /Library/Ruby/Gems/1.8/bin/siriproxy:19:in`load'
    from /Library/Ruby/Gems/1.8/bin/siriproxy:19
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$  cp ./config.example.yml ~/.siriproxy/config.yml
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$ siriproxy gencerts
-bash: siriproxy: command not found
unknown60334b0ed5bb:plamoni-SiriProxy-5ee281c Huntington$

**Comment by huntsept** [comment]
And also attempted it here with this instead of siriproxy gencerts 

/SiriProxy/bin/siriproxy bundle

**Comment by venom420x** [comment]
/SiriProxy/bin/siriproxy bundle 

that wouldn't execute your certificates

sudo port install openssl
your mac should have openssl installed out of box

and 
./siriproxy gencerts

should be siriproxy gencerts no ./ in the command

im not quite understanding what your question/problem is some of your commands just arent type in properly

**Comment by huntsept** [comment]
Last login: Sun Dec 11 13:10:17 on ttys001
unknown60334b0ed5bb:~ Huntington$ siriproxy gencerts
-bash: siriproxy: command not found
unknown60334b0ed5bb:~ Huntington$

**Comment by huntsept** [comment]
it just to make sure with the port install and both commands should have done the trick

**Comment by huntsept** [comment]
But what I'm going to do is run parallel on my mac try using ubuntu and setup the server this way i can migrate it to a mac or pc running ubuntu that i do not turn off in my house :) i'm running it right now ill tell you how it goes.
