### ISSUE TITLE
[Solved... but other error has occured] iPhone 4S is working but iPhone 4 is not working... disconnecting error.

### ISSUE THREAD

**Issue by bexel** [plamoni/SiriProxy#222]
I installed SiriProxy in ubuntu 11.10.

siriproxy gencerts
and installed ca.pem in iPhone 4S and change dns.
and I used siri. (key file is created).

iPhone4 : change dns server -> Change Spire Proxy Server -> Use Siri...

ocessed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#Zlib::Inflate:0x0000000126c6a8, @zip_stream=#Zlib::Deflate:0x0000000126c680, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000126b550 @manager=#<SiriProxy::PluginManager:0x0000000126bdc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000126b320 @signature=117, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000126aec0>, @zip_stream=#Zlib::Deflate:0x0000000126ae98, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000126b000 @manager=#<SiriProxy::PluginManager:0x0000000126a1a0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001260858 @signature=118, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000124dfc8>, @zip_stream=#Zlib::Deflate:0x0000000124c1c8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001230450 @manager=#<SiriProxy::PluginManager:0x0000000122b568 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000122fd20 @signature=119, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000122f7f8>, @zip_stream=#Zlib::Deflate:0x0000000122f7d0, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000122e650 @manager=#<SiriProxy::PluginManager:0x0000000122eee8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000122def8 @signature=120, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000122d9a8>, @zip_stream=#Zlib::Deflate:0x0000000122d980, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000012344d8 @manager=#<SiriProxy::PluginManager:0x0000000122d2a0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000012341e0 @signature=121, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001233df8>, @zip_stream=#Zlib::Deflate:0x00000001233d80, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001232c28 @manager=#<SiriProxy::PluginManager:0x00000001233498 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001232980 @signature=122, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001232430>, @zip_stream=#Zlib::Deflate:0x00000001232340, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001236710 @manager=#<SiriProxy::PluginManager:0x00000001238970 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001236170 @signature=123, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001235d88>, @zip_stream=#Zlib::Deflate:0x00000001235ce8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000123b9e0 @manager=#<SiriProxy::PluginManager:0x000000012353d8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000123b3c8 @signature=124, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000123a4c8>, @zip_stream=#Zlib::Deflate:0x0000000123a270, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000123f928 @manager=#<SiriProxy::PluginManager:0x000000012407d8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000123f4a0 @signature=125, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000123f1f8>, @zip_stream=#Zlib::Deflate:0x0000000123f1d0, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000123d830 @manager=#<SiriProxy::PluginManager:0x0000000123e6b8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000123ce58 @signature=126, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001244b30>, @zip_stream=#Zlib::Deflate:0x00000001244b08, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001243370 @manager=#<SiriProxy::PluginManager:0x000000012441a8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000012430a0 @signature=127, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001242ee8>, @zip_stream=#Zlib::Deflate:0x00000001242ec0, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001241110 @manager=#<SiriProxy::PluginManager:0x00000001242678 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001240ee0 @signature=128, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001247a38>, @zip_stream=#Zlib::Deflate:0x000000012477b8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001245f30 @manager=#<SiriProxy::PluginManager:0x00000001246d68 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001245b20 @signature=129, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001245878>, @zip_stream=#Zlib::Deflate:0x00000001245850, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000124b570 @manager=#<SiriProxy::PluginManager:0x00000001245030 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000124aaa8 @signature=130, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001249a18>, @zip_stream=#Zlib::Deflate:0x00000001249900, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000012547d8 @manager=#<SiriProxy::PluginManager:0x0000000124f300 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001253c98 @signature=131, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001253388>, @zip_stream=#Zlib::Deflate:0x00000001253338, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001258770 @manager=#<SiriProxy::PluginManager:0x00000001251588 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001258540 @signature=132, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001258090>, @zip_stream=#Zlib::Deflate:0x00000001258040, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001255c00 @manager=#<SiriProxy::PluginManager:0x00000001257190 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000012558e0 @signature=133, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000012555e8>, @zip_stream=#Zlib::Deflate:0x00000001255430, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000125a5e8 @manager=#<SiriProxy::PluginManager:0x0000000125c0c8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000125a020 @signature=134, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001259c10>, @zip_stream=#Zlib::Deflate:0x00000001259b20, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000125fb88 @manager=#<SiriProxy::PluginManager:0x00000001260df8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000125f5e8 @signature=135, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000125ed28>, @zip_stream=#Zlib::Deflate:0x0000000125ebe8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000012635d0 @manager=#<SiriProxy::PluginManager:0x0000000125d428 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001262bf8 @signature=136, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001261d20>, @zip_stream=#Zlib::Deflate:0x00000001261c30, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001266f00 @manager=#<SiriProxy::PluginManager:0x00000001268508 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001266870 @signature=137, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000012663c0>, @zip_stream=#Zlib::Deflate:0x000000012662f8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000126be60 @manager=#<SiriProxy::PluginManager:0x0000000126ca68 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000126bcd0 @signature=138, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000126baa0>, @zip_stream=#Zlib::Deflate:0x0000000126ba28, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000126a268 @manager=#<SiriProxy::PluginManager:0x0000000126b3e8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001269250 @signature=139, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001270190>, @zip_stream=#Zlib::Deflate:0x000000012700f0, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000122b590 @manager=#<SiriProxy::PluginManager:0x00000001247a38 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000122a988 @signature=140, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000122a000>, @zip_stream=#Zlib::Deflate:0x00000001229f38, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000122ef10 @manager=#<SiriProxy::PluginManager:0x0000000122fe10 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000122eda8 @signature=141, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000122eb28>, @zip_stream=#Zlib::Deflate:0x0000000122eb00, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000000122d2c8 @manager=#<SiriProxy::PluginManager:0x0000000122e100 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000122d048 @signature=142, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000122ce90>, @zip_stream=#Zlib::Deflate:0x0000000122ce40, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000012334c0 @manager=#<SiriProxy::PluginManager:0x00000001234258 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001233308 @signature=143, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000012330d8>, @zip_stream=#Zlib::Deflate:0x000000012330b0, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001238c18 @manager=#<SiriProxy::PluginManager:0x00000001232a98 @plugins=[...]>>]

How to solve this error..
(Sorry my poor english)

**Comment by earlcochran** [comment]
I believe you are getting this error because the CA is not pointing to your server. It's pointing to guzzoni.apple.com. I've been trying to get this solved.

**Comment by bexel** [comment]
Solved this error, but other error..

[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CancelSpeech
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed

**Comment by earlcochran** [comment]
you're getting that with iPhone 4s?

**Comment by bexel** [comment]
iPhone 4S is working fine.

**Comment by earlcochran** [comment]
How did you solve the error? iPhone 4S is talking to SiriProxy (Test Siri Proxy returns confirmed)? And you're getting what you just pasted from a 4? What are your settings in the CA? Did you modify anything before generating certs?

**Comment by bexel** [comment]
C=KR, ST=Missouri, O=Siri Proxy, CN=SiriProxyCA
Edit gen_certs.sh:
 "guzzoni.apple.com" to "your.ip.add.ress"
and rake install -> siriproxy bundle -> siriproxy server --> install ca.pem to iPhone 4S and set dns(your ip addr, dnsmasq) -> Use Siri -> Install ca.pem to your Old iDevice

iPhone 4S is working fine, but iPhone 4 is ..
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CancelSpeech
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed

Good luck.

**Comment by terriblybored** [comment]
Have you tried using Westbaer's fork? The CommandFailed object might be sent because of a failure to authenticate. This is because you are not using the keys from your iPhone 4S. Westbaer's fork is supposed to be saving the keys.

**Comment by earlcochran** [comment]
I am using the latest version of westbaer's fork. I still can't get both devices to play nice on one proxy.

**Comment by ghost** [comment]
I can confirm that problem and I filed the same issue about 15 hours ago right here. Any solution for that?

**Comment by earlcochran** [comment]
Not to my knowledge. Some people have gotten both devices past handshake, but not actually a 4 getting responses.

**Comment by ghost** [comment]
I can confirm that the keys are saved by westbaers fork in the ~/.siriproxy folder but they dont seem to be merged with the request from the iphone 4.

**Comment by ghost** [comment]
Do you mean the ssl handshake with the proxy?

**Comment by earlcochran** [comment]
@Eliminatrix Yes. My keys are saving to ./siriproxy and my 4S is fine. My iPhone 4 wont complete the handshake.

**Comment by jayb1239** [comment]
I believe the issue is due to the SSL authentication. Do you have the 4s running with dnsmasq and the 4 running via spire? if so your 4S needs the server to auth its self as guzzoni.apple.com and the 4 needs it to be authd as its self (ip address or domain) I got around this by setting up a certificate with dual common names

**Comment by ghost** [comment]
And this worked? If it really worked I would appreciate that you tell us how to set up two common names... :)

**Comment by jayb1239** [comment]
Yes it appears to work but I have only tested it with myself with the 4s on my wifi network and a friend with a 4 and Spire at a remote location and requests appear to be answered fine. only issue at the moment is that we can't both request at the same time via the proxy and sometimes it throws a fit and calls me his name and him me

**Comment by ghost** [comment]
But how did you setup OpenSSL and siriproxy's gencerts for two common names?

**Comment by jayb1239** [comment]
but to do the dual CA I edited /etc/ssl/openssl.cnf and scrolled down to 
common name and changed it to

0.commonName                    = Common Name (eg, YOUR name)
0.commonName_default            = www.domain1.com
0.commonName_max                        = 64
1.commonName                    = Common Name (eg, YOUR name)
1.commonName_default            = www.domain2.org
1.commonName_max                        = 64

i didn't use gencerts i generated my own with: -

(use any password and information you want)
openssl genrsa -des3 -out ca.key 4096
openssl req -new -x509 -days 365 -key ca.key -out ca.crt
openssl genrsa -des3 -out server.key 4096

openssl req -new -key server.key -out server.csr

openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.passless.crt
openssl rsa -in server.key -out server.key.insecure
mv server.key server.key.secure
mv server.key.insecure server.passless.key

and if you do the openssl.cnf hack first then during those commands it will prompt you for common name 1 & 2. Mine was fussy and the first one had to be guzzoni and the second my domain. if i did it the other way it didn't work.

Hopefully that makes sense. never been good at putting into words

**Comment by ghost** [comment]
now it doesnt say ca.pem but ca.crt and thats the file that I need on my phone, right?

**Comment by jayb1239** [comment]
yeah thats the one its just named differently if you view the cert when you install it on your phone it should have 2 common names. you need to make sure that you have put the certs in the ~/.siriproxy folder too and restarted SiriProxy

**Comment by jayb1239** [comment]
did that do it?

**Comment by ghost** [comment]
hmm... the certificate on my phone says as common name "[my ip],guzzoni.apple.com" and when i try speaking to siri the server still says that it failed:

```[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed

```
```

**Comment by jayb1239** [comment]
have you tried clearing the session validation data out of the ~/.siriproxy folder re-starting siriproxy and capturing fresh auth data from the 4s?

**Comment by ghost** [comment]
i will try when my friend comes back ^^ thank you in advance

but is it correct that in my common name on my phone my ip is first listed? not guzzoni?

**Comment by earlcochran** [comment]
@jayb1239 @Eliminatrix I'm having the exact same issue as @Eliminatrix. CA shows up as IP, guzzoni.apple.com. The 4S is working fine, generating files. 4 gets passed handshake but still get SessionValidationFailed

**Comment by ghost** [comment]
any solution on this?

**Comment by earlcochran** [comment]
With dual common names the handshake issue seems to be gone. My 4S gets responses from "test Siri proxy" command. While my 4 will connect but not authenticate.

**Comment by jayb1239** [comment]
@methoddk re create the certs and put guzzoni in common name 1 and your server in 2 if that is the opposite to what you did before

**Comment by earlcochran** [comment]
That's the way I did it. But when I put the CA on my phone it displays as 192.168.5.12, guzzoni.apple.com. Both devices will connect and get responses in console. But the 4 won't let me ask anything to Siri.

Did you actually have the iPhone 4 sharing keys and answering you

**Comment by ghost** [comment]
what if my server would be the first cn and guzzoni the secoud. that would result in appearing as guzzoni.apple.com,[my ip] on the phone

**Comment by jayb1239** [comment]
yes both answering, as i said re generate the certs and put guzzoni first then yours or whatever is the opposite of what you did before so the cert reads guzzoni.apple.com, 192.168.5.12. then try leaving the cert on the 4s as it is and swapping the cert on the 4 for the new one

**Comment by earlcochran** [comment]
Will it? Or is it just displaying the CNs in alphabetic order? I haven't been able to try yet

**Comment by jayb1239** [comment]
it was an idea. I'm stumped then as it works here with the dual ca

**Comment by earlcochran** [comment]
It definitely fixed my issue with the 4 not passing the ssl handshake. If it worked for you I'm sure I'm not doing something right.

**Comment by jayb1239** [comment]
what output are you actually getting in the console

**Comment by ghost** [comment]
i'm getting this message in my siriproxy console:

```
[Info - Guzzoni] SSL completed for Guzzoni

```

does that mean that the ssl cert is alright?

**Comment by earlcochran** [comment]
@jayb1239 i got the cert to display correctly, but still not working on iPhone4. The data is being pulled from the 4S fresh each time i try. The iPhone 4S is working 100% with SiriProxy. Here is a dump of my last attempt, the top portion is the 4S. Bottom half is iPhone 4. Note the lat/long lines on iPhone 4 attempt. (Sidenote, is there an IRC chan already in place to discuss this some more? If not, join #sproxy on EFNet.)

**_iPhone 4S  attempt**_

siriproxybox@siriproxybox:~/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9e284a8 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9e283e0>, @zip_stream=#Zlib::Deflate:0x9e283cc, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9b32474 @manager=#<SiriProxy::PluginManager:0x9e2819c @plugins=[...]>>]
{"speech_id"=>"REMOVED", "assistant_id"=>"REMOVED", "session_data"=>"REMOVED"
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: StartSpeechRequest
{"speech_id"=>"REMOVED", "assistant_id"=>"REMOVED", "session_data"=>"REMOVED"}
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: REMOVED, long: REMOVED
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: AssistantLoaded
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: SetConnectionHeader
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Test Siri proxy '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Example:0x9b32474
[Info - Plugin Manager] Matches (?i-mx:test siri proxy)
[Info - Plugin Manager] Applicable states: 
[Info - Plugin Manager] Current state: 
[Info - Plugin Manager] Matches, executing block
[Info - Plugin Manager] Say: Siri Proxy is up and running!
[Info - Plugin Manager] Sending Request Completed

**_iPhone 4 attempt**_

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9e11550 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9e11488>, @zip_stream=#Zlib::Deflate:0x9e11474, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9e10844 @manager=#<SiriProxy::PluginManager:0x9e11154 @plugins=[...]>>]
{"speech_id"=>"REMOVED", "assistant_id"=>"REMOVED", "session_data"=>"REMOVED"}
[Warning] Non-4S device connected.
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
**[Info - User Location] lat: , long: **(Notice here how theres no lat/long, it didnt pull the data)**
{"speech_id"=>"REMOVED", "assistant_id"=>"REMOVED", "session_data"=>"REMOVED"}
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed

**Comment by earlcochran** [comment]
Additions to last comment:

I fixed location on the iPhone 4. (Turn it on, duh.)

Here is where it appears to be failing:

**_[Info - Guzzoni] Received Object: GetSessionCertificateResponse**_
**_[Info - Guzzoni] Received Object: SessionValidationFailed**_

**Comment by earlcochran** [comment]
I can also confirm that SiriProxy IS sending the data over to the 4. Wasn't getting any nil fields. Maybe a certificate problem?

**Comment by chrisclarkefly** [comment]
I have the same result only my id's come back as nil. I assume that is because I haven't had a 4S connect to my siriproxy yet, and I don't have one to test on.

{"speech_id"=>nil, "assistant_id"=>nil, "session_data"=>nil}

On another note, I was able to use Dynamic DNS and forward port 443 through my router to my proxy server, so I don't have to use my vpn.

**Comment by earlcochran** [comment]
Yes, if you are getting nil than its because it can't find the key files.

I'm thinking this is a CA issue...

**Comment by mcdull** [comment]
I got no progress yet.  IPhone 4S and Iphone 4 both connected. Session / Speech / assistant saved.  but still got SessionValidationFailed.

**Comment by earlcochran** [comment]
You need to get com.apple.assistant.plist off of the iPhone 4 (var/mobile/Library/Preferences) and add these values under Accounts > Hex String:

**_Speech Identifier**_
**_Assistant Identifier**_
**_Ace Host**_

You can set anything you want for the values, SiriProxy will replace them during connect.

**Comment by mcdull** [comment]
is this a hex plist?

**Comment by earlcochran** [comment]
I don't know. I do know though that the string data doesn't matter on the phone.

**Comment by jdcipher** [comment]
This worked great!  thanks - that was the missing link for me...
speaking of links, here's a good one that shows how to add these identifiers:

http://www.stantheripper.com/siri/

**Comment by mcdull** [comment]
Bingo.. got it working now.

2011/12/30 jdcipher <
reply@reply.github.com

**Comment by earlcochran** [comment]
It all seems so simple when it all comes together, doesn't it? :)

**Comment by mcdull** [comment]
It should be the missing part of spire.  But we were all focusing on the
siriproxy.

2011/12/30 methoddk <
reply@reply.github.com

**Comment by chrisclarkefly** [comment]
except if you don't have access to a 4S..

On Thu, Dec 29, 2011 at 9:51 PM, methoddk <
reply@reply.github.com

**Comment by earlcochran** [comment]
I wrote up a short guide form start to finish how I got this working after many hours reading and tweaking, hopefully it helps.

http://methoddk.com/siriguide/

**Comment by mcdull** [comment]
nice tutorial.
Though I recommend to use ifile for plist editing and VPN for easier Iphone
4S access.

2011/12/30 methoddk <
reply@reply.github.com

**Comment by creemerica** [comment]
Finally got it working, but there has to be away around the not being able to use both at the same time thing.

Like, give each device a unique ID instead of just 'iPhone' or something.

Not sure how you would do it, but that would fix the issue of only being able to use one at a time.

**Comment by earlcochran** [comment]
@creemerica I think it does that because its using the 4S's keys for the request. When guzzoni gets two requests for the same key, it does nothing because it doesnt know where to send its response. That's my take on it, I could be wrong.

**Comment by creemerica** [comment]
@methoddk that makes sense.  Just wondering how people would go about setting up public Siri servers with that problem.  Seems to me like a lot of people would be using it at the same time so it wouldnt work.

**Comment by earlcochran** [comment]
@creemerica that's why public servers wouldn't work. Max 2 to 3 people per iPhone 4S key, 3 might actually be pushing it.

**Comment by merlis1** [comment]
Thank you, finally after a week my siriproxy is up and
Running on both 4s and iPhone 4, but only over wifi.
I understand a can use a free dynamic Dns eg. No ip, freedns,
Etc to get into my dynamically addressed ip at home.
Can you please explain how to go from fully working over
Wifi to fully working over 3G. Where would I replace the
Siriproxy host (192.168.1.115) with (scott.bouncemeto.com)?
In the certificate on the 4s? The cert on the iPhone 4? Dnsmasq? On the iPhone
4 do I adjust the plist?? Please help :)

**Comment by earlcochran** [comment]
@merlis1 you need to generate a dual CN cert. Instructions on how to do this are here: https://gist.github.com/1552448 lines 60-98

After you make the cert, install it on both devices. Edit Spire to point to https://your.no-ip-domain.com. Edit com.apple.assistant.plist to point Hostname to the same domain.

**Comment by merlis1** [comment]
Thank you so much for your help. as a n00b, I really do appreciate it.  My siri proxy is up and running on both my iphone 4s and on my iphone 4 over 3g, but i cannot currently get the iphone 4 working over WIFI, originally i had the iphone 4 on wifi , but not on 3g so I created the dual CN, i created the certs, put it on both my iphone 4s and 4.  (the 4s 100% works), the iphone 4 works 100% over 3g using my free no-ip. dns resolution.  The only thing i can think of is in addition to changing the spire proxy to point to my noip address, i updated assistant.plist to use the no ip address and that works, however yesterday i had changed the /etc/hosts file on my iphone 4, this am i pointed it as "xxx.bounceme.net  and resolved it to guzzoni.apple.com " is this why it isnt working over wifi or is it someother issue...? any help would be greatly appreciated...

**Comment by earlcochran** [comment]
@merlis1 For dual CN cert you don't need a hosts entry. Just set Sipre to https://your.no-ip.com and remove whatever you added in hosts.

**Comment by merlis1** [comment]
I did remove the hosts entry, Siri still works over 3G but not wifi, any other suggestion?

**Comment by earlcochran** [comment]
@merlis1 don't edit DNS on iPhone 4. Make sure plist matches spire. What's the order of your hosts for the cert?

**Comment by merlis1** [comment]
Both spire & plist are same both pointed to https://ISP.bounce.me.net etc.. On certificate I made www.domain1. = https:// jsp.bounce.me
And www.domain 2 : guzzoni.apple.com , that's correct isn't it ?

**Comment by earlcochran** [comment]
@merlis cert should be fine if the 4 works over 3G. Try rebooting the phone?

**Comment by merlis1** [comment]
Got it, was a router reset that did it. I just wanted to say thanks again for your taking the time to help me, it's not every day that people go out of their way for others, and more people doing it will make this world a better place. Happy holidays to you and yours :)

**Comment by earlcochran** [comment]
@merlis1 No problem. Glad you got it working.

**Comment by felixlvh** [comment]
Hi can you please help on this?

[Info] Found cached session data.
[Info] Found cached speech id.
[Info] Found cached assistant id.
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed

i am paying $30 for those who can fix my problem, really appreciate your help

Regards
Felix

**Comment by merlis1** [comment]
Did u edit /var/mobile assistant.plist and add the validation key and other 2 Id pieces on the iPhone 4??

**Comment by felixlvh** [comment]
i don't have iphone 4s :P

**Comment by earlcochran** [comment]
@felixlvh well there's your problem...

**Comment by felixlvh** [comment]
is anyone willing to share or sell the key?

**Comment by earlcochran** [comment]
@felixlvh not likely.

**Comment by felixlvh** [comment]
@methoddk ok thanks

**Comment by felixlvh** [comment]
i can't believe they are selling here. LOL

http://search8.taobao.com/search?q=siri+key&commend=all&ssid=s5-e&pid=mm_14507416_2297358_8935934

**Comment by schmooty** [comment]
@merlis1 

I've asked around but no one has given a response or any help about getting to work over 3G. Your te only shot I got at getting this to work I guess. Anyway...

Could you please explain in detail how you got it working over 3G. ? I'm assuming you followed methoddk DYNMIC tutorial. When did you use your no-ip and when did you use your internal ip( virtual Maxine internal ip) and when did you use guzzoni?

1.I'm using for step 2 (Dns masq) I use my internal virtual machine ip
2.I'm using dual commonames with my no-ip FIRST and guzzoni second
3.Changed DNs serring (on the phone itself under wi fi setting) on both phones to internal virtual machine ip
4.host file edited for no-ip followed by guzzoni
5.plist I'm assuming the no-ip but I know I can do this part. I would like to make sure everything else is working before I complete the last step

Thanks in advance. This has been driving me crazy!!!!

**Comment by felixlvh** [comment]
you got it working via wifi?

**Comment by schmooty** [comment]
Yes. Just not over 3G or external wifi. It only works when at at home but both work perfect when they do work

**Comment by felixlvh** [comment]
are you using 4s or 4?

On Fri, Jan 13, 2012 at 10:43 PM, schmooty <
reply@reply.github.com

**Comment by schmooty** [comment]
Felixlvh

Re 4s works period. Whether I'm at home or away or on 3G works perfect.
The 4 works perfect when I'm home on my wifi but if I leave my house = no Siri whatsoever. Does not work on edge/3G/wifi.
But when I get home the 4 will work perfect again

**Comment by earlcochran** [comment]
You don't need to edit hosts when you use a dual common name cert. how does the cert display under Settings > General (scroll to bottom "Profile:")? Is guzzoni listed first?

**Comment by schmooty** [comment]
Methoddk I'm sure glad your helping!!! I need you. Yeah my cert has guzzoni first.  I've got:

For the step 2 on your tutor(DNs masq) my virtual box internal ip after guzzoni
   (example: address=/guzzoni.apple.com/192.168.0.xxx )

I do the dual commnes with my no-ip FIRST and guzzoni second
      -this makes the cert with guzzoni showing
      -side note: I also switched them( so my no-ip showed first) and still nothing 
      This might sound retarded but to clarify when you say to put your no ip first on commoname you mean like this:
                   No-ip
                   Guzzoni

And then the next set of keys 
            No-ip
            Guzzoni
Correct??

Or should it be:
   No-ip
   No-ip
And them for the second se of keys
  Guzzoni
   Guzzoni 

I'm assuming the first. And maybe this will clarify for others too 

Leave the .host file as is
Plist is fine -(works with atatic ip in network using the same one)
Spire set to no-ip 
    - I've only been able to get communication with server using guzzoni.apple.com though. If I do t have that on spite I get no      response from the server whatsoever no matter what config I try either  

Thanks everyone sooooo much

**Comment by earlcochran** [comment]
Your plist should have the no-ip in the Hostname spot as well.

**Comment by schmooty** [comment]
I was missing that part!!! thanks i think its gonna work now!!! 

just to clarify--- so with this config it WILL WORK OVER BOTH ANY WIFI AND EDGE/3G:

1.dns masq in step 2 of guide set to : virtual machine internal ip 192.168.0.xxx
        (example: address=/guzzoni.apple.com/192.168.0.xxx)

2 dual commnames with no-ip first 
           example

commonname1 -  No-ip
commnoname2 -  Guzzoni

And then the next set of keys 

commonname1 - No-ip
commonname2 - Guzzoni

.host do not change and leave default
.plist edit to my no-ip
spire set to my no-ip

any issues or anything wrong with the above or am i good to go???

**Comment by schmooty** [comment]
oh i ALMOST forgot....

THANK YOU!!!!!  THANK YOU!!!!! THANK YOU!!!!! THANK YOU!!!!!

**Comment by ghost** [comment]
Hi,
I installed SiriProxy in ubuntu 11.10, generated ca.crt and sent to my iPhone 4S.
But I can't install it. When I open it the iPhone shows me the Settings page but nothing else...

Does anybody can tell me what's wrong with my iPhone 4S ???
Thanks in advance.

**Comment by earlcochran** [comment]
I've never seen that before. Did you get it worked out?

**Comment by ghost** [comment]
No... I don't understand why... Maybe because it's a lecked iPhone 4S with French carrier ?

**Comment by humour** [comment]
@methoddk I have followed your guide and the my 4S connects fine but I don't know where in my cert I am going wrong as once I add everything to my 4 I get this error over and over

"Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone: @signature=56, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x96907f4>, @zip_stream=#Zlib::Deflate:, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:@manager=#<SiriProxy::PluginManager: @plugins=[...]>>]"

My plist file is already modified with the same host address that's in spire but it still doesn't work

My info for the cert is like this
   0.commonName = Common Name (eg, YOUR name)
   0.commonName_default = dyndns server
   0.commonName_max = 64
   1.commonName = Common Name (eg, YOUR name)
   1.commonName_default = guzzoni.apple.com
   1.commonName_max = 64

and when It asks those questions when creating the cert I entered essentially the same info but still stumped.  Any insight possibly where I went wrong?

**Comment by schmooty** [comment]
@humour 

Nobody really explains or clarifies this part. 

In the dual cn. When your editing the file you literally leave it as it shows default. Don't change out the domain1 and domain2 for your actually info. Leave as is. When it asks for the common name when your making the new keys is when you replace or add in with your dydns/no-ip an then guzzoni 2nd. 

I hope I understood you correctly and I hoped response makes sense. Of it doesn't let me know and I'll be more clear

**Comment by humour** [comment]
@schmooty ha that totally makes sense, I was actually modifying it with my info...I will give it a shot and post back my results

**Comment by schmooty** [comment]
That should do it. Let me know if that does it or not. Funny thing is I've walked several people through getting theirs set up and working but somehow I can't get mine working ( over 3G and remotely). For me its a port forwarding. I cant figure that part out. Anyway, if that doesn't fix it which it should just post what happens and well get it working for you!!

**Comment by humour** [comment]
@schmooty I am trying to accomplish the same thing...4S is not with me at the moment so I can't try my new cert just yet but should be able to shortly...when filling in domain2 should it be https://guzzoni.apple.com or just guzzoni.apple.com? or does it realy even matter?

**Comment by earlcochran** [comment]
just guzzoni.apple.com

**Comment by schmooty** [comment]
Methoddk is correct. But to clarify. Use the https that is there  already. So you don't type any https. You only type "guzzoni.apple.com" without the quotes 
Now just the moment of truth. Pray to god it works!!!  I'm hoping for ya

**Comment by humour** [comment]
@schmooty @methoddk new cert installed on both phones and still getting the same thing on the 4...obviously still doing something wrong with the dual cert.  does it matter if https is listed in front of domain 1 or not?

**Comment by earlcochran** [comment]
https:// should not be anywhere in the cert. only in spire and plist. If you edited hosts file, change it back.

**Comment by humour** [comment]
@methoddk @schmooty you guys are awesome...it is up and running both on wifi and out of network.  Thank you so much

**Comment by schmooty** [comment]
0.commonName = Common Name (eg, YOUR name)
0.commonName_default = www.domain1.com
0.commonName_max = 64
1.commonName = Common Name (eg, YOUR name)
1.commonName_default = www.domain2.org
1.commonName_max = 64

Copy and paste that

**Comment by schmooty** [comment]
Awesome!!  Glad that worked out. Would it be possible get your email. I was gonna ask for your help on one thing and I don't want ro clutter this

**Comment by humour** [comment]
@schmooty send me a pm threw git

**Comment by schmooty** [comment]
@humour 

Is there something wrong with your profile?  it's not letting me pm you

**Comment by humour** [comment]
@schmooty don't think so I checked my profile and my email is there when I try to message you it says you don't have an email listed...do you go on irc at all?

**Comment by schmooty** [comment]
@humour 

Yeah that's what I got when I tried to pm you. Anyway, I fixed my profile so you should be able to email me. I made it publicly available. Thanks by the way. I appreciate it!!

**Comment by humour** [comment]
@methoddk @schmooty So my siripoxy server randomly restarted and now I can't start the actual proxy server again and I have re ran the guide and started fresh multiple times but once I get to rvmsudu siriproxy server it just keeps saying file not found and I have already started fresh...I have even go into the SiriProxy/bin folder and still can't start it any of you seen this before

**Comment by earlcochran** [comment]
You need to be in ~/SiriProxy then run rvmsudo siriproxy server

**Comment by humour** [comment]
@methoddk I am in that dir it says /usr/bin/evn: siriproxy: No such file or directory

**Comment by earlcochran** [comment]
It's not looking in the right directory. Check your ~/.bash_profile is rvm directory set in there?

**Comment by humour** [comment]
@methoddk Yes I see this in the profile $HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

**Comment by earlcochran** [comment]
And you did rvm use 1.9.3? Do that. Try a rake install on siriproxy again.

**Comment by humour** [comment]
I did do that but I will try it again

**Comment by humour** [comment]
@methoddk still the same error, I followed it exact and get the same error on 2 different machines can't believe it.

**Comment by schmooty** [comment]
im glad you posted. after you email the other day i started over as well and same thing. it tells me it cant find the server passless key but i checked and its for sure in the correct folder and im looking in the correct folder. i dont know what happened??? all of a sudden the server wont run. if anyone gets this resolved please post the fix!!

**Comment by schmooty** [comment]
@humour 
if it helps are you using mac os , windows, ubuntu? 

also virtual machine or not?

I have spent so much time on this i can get the server to work with any of the above, but after doing all 3 my favorite was in a windows only enviropnemnt ( no virtual box ubuntu neede). It runs perfecrtly and it runs better and smoother than when the server runs on ubuntu virtual machine and i can tell you how to set up start up scripts so the server will auto run if your machine reboots or restarts etc.the server just loads up and runs by itself!!! . If you prefer windows only let me know ill send you the instructions. I seem to have better going that right. right now I feel like im a router tweak away from having it working perfectly in every way and even be easy and convenient. so let me know. maybe youll get yours working easier that way.

also I'm going to continue to try to get it working on windows and ubuntu virtual box and once i do im gonna post the most detailed step by step EVER so anyone will be able to do it using any methodd

**Comment by humour** [comment]
@schmooty I am using windows and both a VM and straight install on 2 different machines I am using VMware and not virtualbox but it's the same thing and I agree it runs smoother when directly installed but please do send them over that would be great I'll keep messing with the file not found thing I just can't get it started when it was working fine maybe 3 days ago but at that time it was in a VM and that machine rebooted so it was bound to happen

**Comment by earlcochran** [comment]
It shouldn't be looking in that directory for siriproxy. It should be looking somewhere in the ~/.rvm folder.

**Comment by humour** [comment]
I removed both siriproxy folders and .rvm and am running threw it again I found another post someone just started with the same issue I'll see if it happens again I checked the .bash_profile and it's showing the correct path

**Comment by humour** [comment]
Well just wanted to post and say just as I was about to give up getting different errors like "rake" not being installed even though I had just used that command 30 minutes earlier or the continuous file not found it's working again.  Instead of being in ~/SiriProxy I did the last 2 commands in the home directory and it started and is up and running again pretty odd but whatever this time on a machine that has ubuntu loaded as the main os vs a VM like my last one which wasn't very reliable.  Thanks for the help again

**Comment by shanagarwal** [comment]
Hi,

I installed SiriProxy in ubuntu 11.10, generated ca.crt with dual cn and sent it to iPhone 4 & 4s.
I'm able to connect to siriproxy over 3g through my 4 but not through my 4s.

Any suggestions will be appreciated greatly.
Thanks in advance.

**Comment by earlcochran** [comment]
Change the DNS on the 4S in wifi settings to the local server lP running siriproxy.

**Comment by shanagarwal** [comment]
but that limits the usage to WiFi.

**Comment by earlcochran** [comment]
On the 4S. Yeah. Siri still
Works normally when off wifi. Just not on Siriproxy.

**Comment by shanagarwal** [comment]
does that mean siriproxy cant be accessed via 3g.

**Comment by earlcochran** [comment]
Over the 4S, yes.

**Comment by shanagarwal** [comment]
is there a way i can grab auth from 4s since i dont have regular access to it.

**Comment by ghost** [comment]
Of course you can use 4S with SiriProxy over 3G. Just put your WAN IP on the dnsmasq.conf
I use my iPhone 4 and my 4S both over 3G, and everything is working fine !
Don't forget to restart the DNS Server... (sudo /etc/init.d/dnsmasq restart) ^^

**Comment by schmooty** [comment]
@knoopix 

you might have just given me the answer ive been lookikng for for over a month now!!!!!!!! Ive spent hours every day looking and asking everywhere and not one person has mentioned or suggested to put in your WAN IP in the dms masq rather than your internal server (pc) ip. 

would you be so kind as to just clarify for me where and when you put in your WAN IP and where and when you put in your intenal server (pc) ip to get it to work over 3g/external wifi ( for: dms masq, certs, host file. plist, phone dns setting, etc).
                  - for me my WAN IP would be 173.164.x.x  and my pc (internal ip) would be 192.168.x.x

I just want to make sure i have everything set up correctly  to get it working over 3G/EXTERNAL WIFI and didn't miss anything else. especially if im making a tweak in one place i need to know if anything else needs to be tweaked. 

im assuming dms masq is your wan ip       --   173.164.x.x
cert is set to wan ip ( im using a static or no-ip) -- 173.164.x.x / no-ip
host file does not change or get tweaked at all -- no change leave default
plist is your wan ip   --    173.164.x.x
phone setting (dns) can be default or internal server (pc)  -- default dns / 192.168.x.x

Thanks in advance

**Comment by ghost** [comment]
@schmooty,

You're welcome. Here is my config to have Siri working over 3G and Wifi :
- dnsmasq is set to WAN IP : 82.128.x.x
- dual cert with no-ip and guzzoni, like here https://gist.github.com/1552448 (line 60-98)
- plist is either WAN IP or no-ip (the same as Spire config) ie: https://my.no-ip.com:443 or https://85.128.x.x:443
- On iPhone 4S, DNS Wifi server is WAN IP
- Host file on mi iPhone 4 use WAN IP to works over Wifi: 85.128.x.x guzzoni.apple.com (but I often use 3G rather than wifi)
- on iPhone 4, use iFile and modify the file  /var/mobile/Library/Preferences/com.apple.assistant.plist and add :
  Ace Host,
  Assistant Identifier,
  Speech Identifier

That's all I have and everything is working fine ^^ Hope this will help you

**Comment by shanagarwal** [comment]
I'm able to use siri proxy on my iphone 4 over 3g but as soon as i shift my friends 4s to 3g it no longer connects to the siri proxy server. i have certificate installed, ports forwarded. any ideas what the problem could be??

**Comment by mcdull** [comment]
@shanagarwal 
You will have to JB your frds iphone to insert the custom host name in the hosts file under /etc/.
or you need to set up a VPN for your frd to connect to.

**Comment by shanagarwal** [comment]
will editing assistant.plist on 4s solve the problem

**Comment by ghost** [comment]
@shanagarwal

Try to put your WAN IP on the iPhone 4S Wifi DNS. Make sure that's the same IP on your dnsmasq.conf (If not, put it and sudo /etc/init.d/dnsmasq restart)
After that, put 4s on airplane mode, and disable it. Try Siri...

**Comment by shanagarwal** [comment]
@knoopix 

i did that but still no progress.

**Comment by ghost** [comment]
@shanagarwal

Are you sure that Wifi is on and certificate is installed on 4S? Did you open both 443 and 53 ports on your router and forward it to your LAN IP? Did you make a restart?

What is your dnsmasq.conf?

**Comment by humour** [comment]
If I wanted my 4S to access my siriproxy even outside of the wifi network so the keys are always saved do I need to modify my dnsmasq with my WAN ip and not internal ip? or Can I just jailbreak the 4S and add guzzoni.apple.com to point to my no ip in the hosts file? or both?  My 4 works in and outside network but atm the keys are expired and I won't be around my proxy server to re auth the keys until probably tomorrow.  So just trying to make it easier

**Comment by ghost** [comment]
@humour

Yes, you need to put your WAN IP in dnsmasq and use it in Wifi DNS too. No need to jailbreak 4S...

Regards

**Comment by shanagarwal** [comment]
@humour 

i performed a jailbreak on my friends 4s, added ifile on the device, made the following changes to assistant.plist - https://guzzoni.apple.com > dns, and it works flawless over 3g or any  other network.

**Comment by schmooty** [comment]
@ shanagarwal

When you say:
Guzzoni.apple.com > dns 

Do you mean you replaced Guzzoni for your DNs or you added it after (one space)? Not sure how to interpret that. Sorry and thanks

**Comment by schmooty** [comment]
Has anyone tried just ssh/ifile from a jailbreak 4s and attempted to copy files from the 4s to a 4 and get the proxy working on the 4 locally and over 3G. Seems that would be much  easier and less confusing than all the editing on files were having to do now

**Comment by humour** [comment]
@knoopix just curious how that allows the 4S to connect to the proxy server when on 3G, I guess how would it know to go to that ip and not guzzoni.

@shanagarwal thanks for the info

@schmooty I believe he means replace guzzoni with your wan ip and to answer your second question I believe this is what you are asking about https://github.com/n00neimp0rtant/Sirious it doesn't require a proxy.  He does mention though that the proxy would be easier but this method is not fully automated.  You still have to do it everyday for now

**Comment by ghost** [comment]
@humour

It's just a question of port forwarding and dnsmas.conf... For me, everything works over 3G with my 4S ! ^^

**Comment by humour** [comment]
@knoopix does it actually communicate with the proxy server over 3G though or are you saying it works over 3G in general?

**Comment by ghost** [comment]
@t humour,

If I'm not on the same network as my proxy server, I only put the wan ip on the Wifi DNS settings and use Siri to grab keys on my proxy server. But I need my 4S connected to Wifi (even it's not mine)...

**Comment by humour** [comment]
@knoopix that makes sense appreciate the info!

**Comment by ghost** [comment]
@humour

You're welcome!

**Comment by TobyTech** [comment]
_BUMP_ Oops, sorry I bumped ya!

PROBLEM: iPhone 4S and iPad 2 will not connect to SiriProxy (WestBaer) over 3G or external Wifi networks.

WHAT I HAVE:

-I have Mac OSX Lion running an Ubuntu (Latest Version) machine.

-SiriProxy up and running over local Wifi

-Patience... I must have LOTS of it......

WHAT I HAVE DONE:

-In MAC dnsmasq.conf, I have: 

##########
#The first one is for the WIFI server
address=/guzzoni.apple.com/192.168.1.12
##########
#This second one is for the 3G Beta Server
address=/guzzoni.apple.com/192.168.1.15
##########
(Ignore the first one, I am using the second one, 1.15)

-In UBUNTU dnsmasq.conf:

address=/guzzoni.apple.com/192.168.1.15

In SiriProxy, I have:

-dual certs (Yes I know about the 2 common names and their order, I GOT IT RIGHT! :D)

-In .plist, I have for hostname:

https://**********.zapto.org

-In Spire: I have:

https://**********.zapto.org

-In /etc/hosts, I have:

Nothing.....

I think this is where I messed up.... I have no ports forwarded. I know how to do it, but which ports do I forward, and what do I put in no-ip.org??

**Comment by earlcochran** [comment]
@Toby:

You need to forward port 443 to the box running SiriProxy.

**Comment by TobyTech** [comment]
I heard that, and I have no frickin clue how to do that. I have a verizon MI424 router. Does anyone here have that?

**Comment by kirb** [comment]
@TobyTech You should be able to go to `192.168.1.1` and set it to forward port 443 to your machine's IP, provided you know the username and password. 
Also, for your 3G server, it should be set to your [external IP address](http://whatismyip.org).

**Comment by TobyTech** [comment]
Thanks! 
- Both Mac and Ubuntu dnsmasq.confs should be set to external?
- is there a certain thing port to internal machine is called? A special name so I can find it?

**Comment by earlcochran** [comment]
It should be called "Port Forwarding"

**Comment by TobyTech** [comment]
Smart-Arse.

**Comment by earlcochran** [comment]
I was being 110% serious. /unsubscribe

Good luck.

**Comment by schmooty** [comment]
In your router it should be under an advance setting option. Look for virtual server or port forward. Enter your ext ip and port 443. If it ask tcp/udp choose both. Not too familiar with your router so hope that helps

**Comment by humour** [comment]
Anyone come across siri not working on there 4S anymore?  It started on friday and it just doesn't work either directly to apple or my proxy server which I see the keys being saved and the request being sent but no response.  I have turned siri off in settings rebooted the phone multiple times but nothing.  I have removed the cert from the phone and dns info from wifi on the 4S to make sure it was going directly to apple and even on 3G testing it and obviously it doesn't work on my i4 either.  It's my own personal proxy server so nobody else is accessing it and I rarely use it on my 4 so there is no way it could have been blocked if that is even possible.  Any recommendations?

**Comment by kirb** [comment]
@humor Apple added more security to the Siri protocol and now many SiriProxies don't work.

**Comment by schmooty** [comment]
@humour 

I finally have mine working perfect using windows. It still works so let me know if you wanna give it a shot. I can give you the instructions (same ones I sent before) but with the proper tweaks to actually make it work (edge,3G and any wifi)

**Comment by humour** [comment]
@kirbylover4000 that's interesting I'll test out my 4S again tomorrow not trying to connect to the proxy to see if it finally starts working again or maybe I'll do a restore but not sure how that will help I only read that in some of the apple discussion forums

**Comment by humour** [comment]
@schmooty that would be great please do send it over!

**Comment by kirb** [comment]
@humor I've heard deleting /var/mobile/Library/Preferences/com.apple.assistant.plist on your phone, then respringing and retrying works, you might want to try that.

**Comment by schmooty** [comment]
@humour ive heard the same as kirby. and ill send it over asap. i still have your email from out pm :)

**Comment by humour** [comment]
@kirbylover4000 @schmooty thanks for the tip on removing that plist it worked.

**Comment by TobyTech** [comment]
@kirbylover4000 

Should I set the 3G server's IP address as the WAN address on the Macintosh dnsmasq.conf, or the Ubuntu dnsmasq.conf? Or both?

Still lookin for how to get ports to forward to an IP on a MI-424WR router :D!

**Comment by kirb** [comment]
@TobyTech I think the 3G server should be used. Remember to use your external IP though.
Here's a port forwarding guide for your router: http://portforward.com/english/routers/port_forwarding/Actiontec/MI-424-WR
You want ports 433 (for SiriProxy) and 53 (for dnsmasq) to be forwarded to your 3G server. I think you also need to do ports from 1023 onward for dnsmasq queries or something, though I'm not really sure on that.

**Comment by TobyTech** [comment]
@kirbylover4000

Port Forward: http://i.imgur.com/cW2rU.png

No-IP: http://i.imgur.com/yt147.png

Macintosh Dnsmasq conf: http://i.imgur.com/GkbLU.png

Ubuntu Dnsmasq.conf: http://i.imgur.com/GkbLU.png       (I know they are the same)

Is this right? I think the port forwarding is messed up. I know how to port forward, but not a port to an internal IP address.

**Comment by kirb** [comment]
@TobyTech The No-IP and dnsmasq config looks correct. The port forwarding should be port 443 to 192.168.1.12 port 443 and port 53 to 192.168.1.12 port 53.

**Comment by TobyTech** [comment]
@kirbylover4000 

I can't tell how I do a port forward that does port to internal IP, I just cant find it....... I think it is right in front of me but I cant see it..... 

MI-424WR router everyone!

**Comment by TobyTech** [comment]
I have an idea...

**Comment by TobyTech** [comment]
Let's play a game!

From HERE, I choose........  http://i.imgur.com/Kay66.png
